// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/05e9c858cf55270a48b1234e613fa9b26da8be23/angular-ui-router-default/index.d.ts
declare module 'angular-ui-router-default' {
// Type definitions for angular-ui-router-default 0.5
// Project: https://github.com/nonplus/angular-ui-router-default
// Definitions by: Stepan Riha <https://github.com/nonplus>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import * as aur from 'angular-ui-router';

module 'angular' {
	namespace ui {
		export type StateDefaultSpecifier = string
			| ((...args: any[]) => string)
			| ((...args: any[]) => ng.IPromise<string>)
			| (string | ((...args: any[]) => string))[]
			| (string | ((...args: any[]) => ng.IPromise<string>))[];
		interface IState {
			default?: StateDefaultSpecifier
		}
	}
}
}
